"""Custom glyphs uploaded into the C128's VDC character RAM.

The VDC keeps its character definitions in its own RAM, not in ROM, so the ones
Claude Code needs and PETSCII lacks can simply be drawn. The C128 KERNAL loads
512 definitions at the base in R28: the first 256 are the uppercase/graphics
set, the second 256 the lowercase set the bridge encodes to. Only unused slots
in that second bank are overwritten, so ordinary text keeps the authentic
Commodore letterforms.

Each glyph is an 8x8 bitmap written as art so it can be read and edited
directly. The VDC reserves 16 bytes per definition; rows 8-15 are not displayed
in an 8-pixel character box and are cleared.
"""

# Codes in the lowercase bank that the PETSCII table already claims for real
# glyphs. Redefining any of these would corrupt the Claude Code logo or the box
# drawing, so they are skipped. Kept here rather than imported from petscii to
# avoid a circular import; test_font_slots_are_free checks the two agree.
RESERVED = {0xA0, 0xE1, 0xE2, 0xEC, 0xFB, 0xFC, 0xFE, 0xFF}

# Allocate from the reverse-video half, which PETSCII barely uses. Starting at
# $C0 leaves plenty of room to add glyphs later without reshuffling.
FREE_SLOTS = [c for c in range(0xC0, 0x100) if c not in RESERVED]

GLYPH_ART = {
    # Prompt chevron. Claude Code's input marker.
    "❯": """
    ..##....
    ...##...
    ....##..
    .....##.
    ....##..
    ...##...
    ..##....
    ........
    """,
    # Tool-use bullet.
    "⏺": """
    ........
    ..####..
    .######.
    .######.
    .######.
    .######.
    ..####..
    ........
    """,
    # The Claude asterisk, used in the banner and as a spinner.
    "✳": """
    ........
    ..#.#...
    ...#....
    .#####..
    ...#....
    ..#.#...
    ........
    ........
    """,
    # Tool-result elbow. A vertical that turns right at the bottom.
    "⎿": """
    ...##...
    ...##...
    ...##...
    ...##...
    ...##...
    ...##...
    ...#####
    ...#####
    """,
    # Stopwatch, shown beside elapsed time.
    "⏱": """
    ..###...
    .#...#..
    #..#..#.
    #..##.#.
    #.....#.
    .#...#..
    ..###...
    ........
    """,
    # Pause, shown when the session is interrupted.
    "⏸": """
    ........
    .##..##.
    .##..##.
    .##..##.
    .##..##.
    .##..##.
    .##..##.
    ........
    """,
    # Ellipsis: three dots on the baseline, one cell wide.
    "…": """
    ........
    ........
    ........
    ........
    ........
    ........
    ##.##.##
    ........
    """,
    # Middle dot, used as a separator in the status line.
    "·": """
    ........
    ........
    ........
    ...##...
    ...##...
    ........
    ........
    ........
    """,
    # Left arrow.
    "←": """
    ........
    ...#....
    ..#.....
    .#######
    ..#.....
    ...#....
    ........
    ........
    """,
    # Rounded box corners. PETSCII has these but charset 2 reassigns them to
    # letters, so they are redrawn here.
    "╭": """
    ........
    ........
    ........
    .....###
    ....##..
    ...##...
    ...##...
    ...##...
    """,
    "╮": """
    ........
    ........
    ........
    ###.....
    ..##....
    ...##...
    ...##...
    ...##...
    """,
    "╰": """
    ...##...
    ...##...
    ...##...
    ....##..
    .....###
    ........
    ........
    ........
    """,
    "╯": """
    ...##...
    ...##...
    ...##...
    ..##....
    ###.....
    ........
    ........
    ........
    """,
    # Check and cross, used in permission prompts and todo lists.
    "✓": """
    ........
    ......#.
    .....#..
    #...#...
    .#.#....
    ..#.....
    ........
    ........
    """,
    "✗": """
    ........
    .#....#.
    ..#..#..
    ...##...
    ...##...
    ..#..#..
    .#....#.
    ........
    """,
    # ASCII that charset 2 gets wrong. Backslash, braces and tilde all land on
    # codes the lowercase set reassigns to letters or box drawing, so `\` came
    # out as "M" - unacceptable in a tool people read code in.
    "\\": """
    ........
    ##......
    .##.....
    ..##....
    ...##...
    ....##..
    .....##.
    ........
    """,
    "{": """
    ....##..
    ...##...
    ...##...
    ..##....
    ...##...
    ...##...
    ....##..
    ........
    """,
    "}": """
    ..##....
    ...##...
    ...##...
    ....##..
    ...##...
    ...##...
    ..##....
    ........
    """,
    "~": """
    ........
    ........
    ........
    .##..#..
    #..##...
    ........
    ........
    ........
    """,
    "^": """
    ...##...
    ..####..
    .##..##.
    ........
    ........
    ........
    ........
    ........
    """,
    # Fisheye, used by the effort indicator.
    "◉": """
    ........
    ..####..
    .#....#.
    .#.##.#.
    .#.##.#.
    .#....#.
    ..####..
    ........
    """,
}


# Characters that should render as an existing glyph rather than consume a slot
# of their own. Claude Code picks from a family of circles and asterisks
# depending on state, and any of them left uncovered falls back to a letter "o"
# or an "*", which is what was showing on the real machine.
ALIASES = {
    "●": "⏺",    # black circle -> the filled bullet
    "○": "◉",    # white circle -> the fisheye outline
    "⏹": "⏺",    # stop
    "•": "·",    # bullet -> middle dot
    "‣": "❯",    # triangular bullet
    "✻": "✳",    # teardrop asterisk -> the Claude asterisk
    "✶": "✳",
    "✷": "✳",
    "✴": "✳",    # eight-pointed
    "✽": "✳",
    "★": "✳", "☆": "✳",
    "→": "❯",    # arrows reuse the chevron
    "▸": "❯", "▶": "❯", "›": "❯",
    "↳": "⎿",    # down-then-right -> the result elbow
    "⌐": "─",
    "\ue0b0": "│",   # powerline separators are just dividers here
    "\ue0b1": "│",
    "\ue0b2": "│",
    "\ue0b3": "│",
}


def _rows(art: str):
    rows = [line.strip() for line in art.strip().splitlines()]
    if len(rows) != 8:
        raise ValueError(f"glyph must be 8 rows, got {len(rows)}")
    out = []
    for r in rows:
        if len(r) != 8:
            raise ValueError(f"glyph row must be 8 columns, got {len(r)!r}")
        out.append(sum(1 << (7 - i) for i, c in enumerate(r) if c != "."))
    return out


# char -> screen code, and screen code -> 8 byte bitmap
CODES = {}
BITMAPS = {}
if len(GLYPH_ART) > len(FREE_SLOTS):
    raise RuntimeError(
        f"{len(GLYPH_ART)} custom glyphs but only {len(FREE_SLOTS)} free slots")

for _i, (_ch, _art) in enumerate(GLYPH_ART.items()):
    _code = FREE_SLOTS[_i]
    CODES[_ch] = _code
    BITMAPS[_code] = _rows(_art)

LAST_SLOT = FREE_SLOTS[len(GLYPH_ART) - 1]

# Aliases resolve to an already-allocated glyph, or are dropped if their target
# is a plain PETSCII character that petscii.GLYPHS already handles.
for _alias, _target in ALIASES.items():
    if _target in CODES:
        CODES[_alias] = CODES[_target]


def definitions():
    """(code, 8-byte bitmap) pairs, ready for the wire."""
    return sorted(BITMAPS.items())


def render(ch: str) -> str:
    """Draw a glyph as art again, for eyeballing in a test."""
    code = CODES[ch]
    return "\n".join(
        "".join("#" if b & (1 << (7 - x)) else "." for x in range(8))
        for b in BITMAPS[code]
    )
