"""Claude's VIC session frame; the complete VDC terminal remains independent."""
from pathlib import Path
from launcher_scene import pointer_shape
from src.native.graphics.font import font

CELLS = [(1,1,12,4),(14,1,25,4),(27,1,39,4),(1,21,11,24),(29,21,39,24)]
RECTS = [tuple(n*8 for n in rect) for rect in CELLS]
LABELS = ['Connect','Repaint','Desktop','Prev','Next']
ICONS = [bytes([0,64,96,112,120,112,96,64]),
         bytes([0,60,66,130,158,128,66,60]),
         bytes([0,16,56,124,254,68,84,124]),
         bytes([0,4,12,28,60,28,12,4]),
         bytes([0,32,48,56,60,56,48,32])]
STATUS = ['Tab selects; Enter activates.', 'Terminal input / Help repaints',
          'Closing... F8 forces return', 'Controls: Tab/Enter; Esc terminal']


def text(data, x, y, value):
    glyphs = font()
    for col, code in enumerate(value.encode('ascii'), x):
        assert 0 <= col < 40
        at = y*320+col*8
        data[at:at+8] = glyphs[(code-32)*8:(code-31)*8]


def enabled(index, live=0, top=0):
    return index == 2 or index == 0 and live == 0 or index == 1 and live == 1 or index == 3 and top == 9 or index == 4 and top == 0


def surface(panel=None, colors=None, glyphs=None, *, live=0, menu=0, top=0, focus=0):
    """All 9,216 owned bytes, using actual terminal glyphs for raw panel codes."""
    assert top in (0,9) and live in (0,1,2)
    data = bytearray(bytes(8192)+b'\x16'*1024)
    text(data,1,0,'uOS / Claude')
    text(data,1,4,STATUS[3 if live == 1 and menu else live])
    text(data,13,22,'Panel '+('10-25' if top else '01-16'))
    text(data,1,24,'Ctrl+Help controls  F8 desktop')
    for index, (x0,y0,x1,y1) in enumerate(CELLS):
        color = 7 if index == focus and enabled(index,live,top) else 0x1b if enabled(index,live,top) else 0xb6
        for y in range(y0,y1):
            data[8192+y*40+x0:8192+y*40+x1] = bytes([color])*(x1-x0)
            for x in range(x0,x1):
                at = y*320+x*8
                if y == y0:data[at] = 255
                if y == y1-1:data[at+7] = 255
                for line in range(8):
                    if x == x0:data[at+line] |= 128
                    if x == x1-1:data[at+line] |= 1
        at = (y0+1)*320+(x0+1)*8
        data[at:at+8] = ICONS[index]
        text(data,x0+3,y0+1,LABELS[index])
    if panel is not None:
        assert len(panel) == len(colors) == 1000 and len(glyphs) == 4096
        for row in range(16):
            for col in range(40):
                source = (row+top)*40+col
                code = panel[source]
                at = (row+5)*320+col*8
                data[at:at+8] = glyphs[code*16:code*16+8]
                data[8192+(row+5)*40+col] = (colors[source]&15)*16+6
    data[8000:8128] = pointer_shape()
    data[9208:9210] = b'\x7d\x7e'
    return bytes(data)


def packed(data):
    result = bytearray()
    index = 0
    while index < len(data):
        end = index+1
        while end < min(index+255,len(data)) and data[end] == data[index]:end += 1
        result += bytes([end-index,data[index]])
        index = end
    return bytes(result)


def write_assembly(directory):
    directory = Path(directory)
    blocks = [('cg_scene',surface())]
    for index, value in enumerate(STATUS):
        data = bytearray(320);text(data,1,0,value)
        blocks.append((f'cg_status_{index}',bytes(data)))
    for page in (0,9):
        data = bytearray(320);text(data,13,0,'Panel '+('10-25' if page else '01-16'))
        # Preserve the two bordered buttons sharing this row.
        full = surface(top=page)
        data[:11*8] = full[22*320:22*320+11*8]
        data[29*8:] = full[22*320+29*8:23*320]
        blocks.append((f'cg_page_{page}',bytes(data)))
    lines = ['; Generated by native_claude_scene.py. Count/value RLE, counts 1..255.']
    for name, data in blocks:
        lines.append(name+':')
        data = packed(data)
        for at in range(0,len(data),24):lines.append(' .byte '+','.join(map(str,data[at:at+24])))
    (directory/'scene.inc').write_text('\n'.join(lines)+'\n')
